language: csharp
solution: "./VoluntariosNaEscola.sln"
install:
- apt-get install mono-devel mono-gmcs nunit-console
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./VoluntariosNaEscola.sln
script:
- xbuild ./VoluntariosNaEscola.sln
