language: csharp
solution: "./VoluntariosNaEscola.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./VoluntariosNaEscola.sln
script:
- xbuild ./VoluntariosNaEscola.sln
